-- a168.`member` definition

CREATE TABLE `member` (
  `mem001` int(11) NOT NULL AUTO_INCREMENT,
  `mem002` varchar(30) NOT NULL,
  `mem003` varchar(65) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL,
  `mem004` varchar(30) NOT NULL,
  `mem005` timestamp NOT NULL DEFAULT current_timestamp(),
  `mem006` int(11) NOT NULL,
  `mem007` int(11) NOT NULL,
  `mem008` int(11) NOT NULL,
  `mem009` int(11) NOT NULL DEFAULT 0,
  `mem010` int(11) NOT NULL,
  `mem011` int(11) NOT NULL,
  `mem012` int(11) NOT NULL,
  `mem013` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `mem014` char(15) DEFAULT NULL,
  `mem015` int(11) NOT NULL DEFAULT 0 COMMENT 'login_error',
  `mem016` enum('Y','N') NOT NULL DEFAULT 'Y' COMMENT 'enable',
  `mem017` enum('Y','N') NOT NULL DEFAULT 'Y' COMMENT 'canbet',
  `mem018` enum('Y','N') NOT NULL DEFAULT 'Y' COMMENT 'chg_pw',
  `mem019` enum('Y','N') NOT NULL DEFAULT 'N' COMMENT 'is_test',
  `mem020` enum('Y','N') NOT NULL DEFAULT 'N' COMMENT 'be_traded',
  `mem021` int(11) NOT NULL DEFAULT 0,
  `mem022` varchar(20) NOT NULL COMMENT '電話',
  `mem022a` int(11) NOT NULL COMMENT '電話簡碼',
  `mem023` tinyint(4) NOT NULL DEFAULT 0,
  `mem024` int(11) NOT NULL DEFAULT 0 COMMENT 'mem_risk',
  `mem026` int(11) NOT NULL DEFAULT 0,
  `mem028` varchar(20) NOT NULL COMMENT '備註',
  `type` int(11) NOT NULL COMMENT '0:現金;1:信用;2:電投',
  `currency` int(11) NOT NULL COMMENT '幣別',
  `cash` decimal(15,4) NOT NULL DEFAULT 0.0000 COMMENT '現金',
  `money` decimal(10,4) NOT NULL DEFAULT 0.0000 COMMENT '己出碼額度',
  `lockmoney` decimal(10,4) NOT NULL DEFAULT 0.0000 COMMENT '鎖定金額',
  `head` int(11) NOT NULL DEFAULT 0 COMMENT '頭像ID',
  `chips` varchar(500) NOT NULL DEFAULT '0' COMMENT '籌碼選擇',
  `follow1` varchar(1000) NOT NULL DEFAULT '0' COMMENT '注關會員',
  `follow2` varchar(3000) NOT NULL DEFAULT '0' COMMENT '關注荷官',
  `tip` enum('Y','N') NOT NULL DEFAULT 'Y',
  `red` enum('N','Y') NOT NULL DEFAULT 'N' COMMENT '红包开关',
  `wallet` enum('Y','N') NOT NULL DEFAULT 'N',
  `opengame` varchar(255) NOT NULL COMMENT '輸入要開啟的種類',
  `site` varchar(60) DEFAULT NULL,
  `lineid` varchar(50) DEFAULT NULL COMMENT 'Line ID',
  `kickperiod` int(3) NOT NULL DEFAULT 10 COMMENT '踢出局數',
  `identity` int(11) NOT NULL COMMENT '0:信用,1:api',
  `singlebetprompt` decimal(15,0) NOT NULL DEFAULT 0 COMMENT '單注金額告警',
  `conwinprompt` int(11) NOT NULL DEFAULT 0 COMMENT '連贏局數告警',
  `winlossprompt` enum('0','1') NOT NULL DEFAULT '0' COMMENT '最大可輸可贏提示',
  `onlineprompt` enum('0','1') NOT NULL DEFAULT '0' COMMENT '上線提示',
  `profitprompt` int(11) NOT NULL DEFAULT 0 COMMENT '盈利告警',
  PRIMARY KEY (`mem001`),
  UNIQUE KEY `mem002` (`mem002`),
  KEY `mem007` (`mem007`),
  KEY `mem008` (`mem008`),
  KEY `mem009` (`mem009`),
  KEY `mem010` (`mem010`),
  KEY `mem011` (`mem011`),
  KEY `mem006_mem022` (`mem006`,`mem022`)
) ENGINE=InnoDB AUTO_INCREMENT=941471 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;